spring.application.name=hotels

logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@mibda2_high?TNS_ADMIN=${TNS_ADMIN:Wallet_MIBDA2}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fullstack1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:FS1DuocJava123.@}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

server.port=8080
